### ISSUE TITLE
Empty Space prefix to section name if no icon provided

### ISSUE THREAD

**Issue by Sairam90** [blackary/st_pages#104]
The section names get prefixed by an extra space where icon value is empty - due to this part of the [code](https://github.com/blackary/st_pages/blob/main/src/st_pages/__init__.py#L78) which is not intended I guess

[nav.txt](https://github.com/user-attachments/files/16540584/nav.txt)
[sample_sections.txt](https://github.com/user-attachments/files/16540588/sample_sections.txt)

**Comment by Sairam90** [comment]
If this is verified I could add a fix - Could you add me as a contributor ?

**Comment by blackary** [comment]
Great catch! Feel free to make a pull request with a fix!

**Comment by Sairam90** [comment]
Am unable to push my local feature branch to the repo 
`Permission to blackary/st_pages.git denied`
Is it something on my side ?

**Comment by blackary** [comment]
You'll need to create a fork of the repo and create a PR from that fork. 

You should be able to run the whole suite of tests by just running `tox`, but you can also just let them run automatically on github when you create the PR

**Comment by blackary** [comment]
Closed by #105
