### ISSUE TITLE
The session state of different pages are not independent

### ISSUE THREAD

**Issue by CaiL230** [blackary/st_pages#109]
I have two pages, each with the same state's name. When I assign a state to one page, the state of another page will also be written with the same value

**Comment by blackary** [comment]
This really doesn't have anything to do with st_pages, but is simply how Streamlit session state works -- it persists for the whole session, no matter which page you are on. 

If you need an easy workaround, you might consider doing something like to add a little prefix to each key, based on which page you want it to be used on:

```
# page 1 code
st.session_state["page1.foo"] = "bar"
...
# page 2 code
st.session_state["page2.foo"] = "baz"
```

Or just give the keys different names altogether.
