### ISSUE TITLE
Suggestion: Make sections have a 'start' and an 'end'

### ISSUE THREAD

**Issue by jordangrodecki** [blackary/st_pages#19]
I would quite like the ability to have pages _not_ in sections, after a section, i.e.

Page 1
Page 2
Section
     - Page 3
     - Page 4
Page 5

I don't believe you can do this because you can't 'end' sections at present, correct?

**Comment by jordangrodecki** [comment]
Syntax is a little challenging as I wouldn't want it to be a breaking change. 

Ideally I'd have preferred Section to be an object which contained multiple Pages so you would just place the Section and not have an 'End' - but that's a big structural change!

I guess something like EndSection('Name') would have to do? Might be cleaner if there was an optional 'key' to use rather than repeating out the whole verbose name each time. 

I don't love that though. Will have a think, and actually look at the underlying code to see how things work :)

**Comment by mfriedy** [comment]
What about an additional parameter for the Page() constructor that was `in_section` which defaults to True, but can be overridden to create a non-sectioned page?

**Comment by blackary** [comment]
@mfriedy That sounds like a great idea! I'll probably get around to adding that eventually, but if someone else wants to put in a PR, that would be great.

**Comment by blackary** [comment]
Now available in 0.4.0 thanks to #29
