### ISSUE TITLE
Data uploading problem in postgre sql table.

### ISSUE THREAD

**Issue by Priyanka260895** [blackary/st_pages#30]
I have one folder where continuous raw files are generated and my program takes these files from that folder reads it and uploads it into postgre sql and then moves into another folder but when i click on stop button files are moved into another folder. In postgre sql table is created but there is no data in table.
What I want is when i click on stop button iteration should be stopped and data should be uploaded into postgre sql table.
i am using below code for this. If there is any solution it would be great help.
This file i am getting error
[code.zip](https://github.com/blackary/st_pages/files/11109552/code.zip)

**Comment by blackary** [comment]
That sounds like a problem unrelated to st_pages. Please consider posting your question on the forum at https://discuss.streamlit.io
