### ISSUE TITLE
Sections don't indent and clicking section names returns to main.py

### ISSUE THREAD

**Issue by ABooth01** [blackary/st_pages#31]
Hi I am having an issue where I cant seem to get the sections to indent and in app these section names can be clicked on just like page titles. Doing so returns the user back to the main app. I have updates to version 0.3.5 and the issue remains. Any ideas what might be causing this behaviour?

**Comment by blackary** [comment]
Are you using `add_page_title()` on each of your pages? If not, then you need to use `add_indentation()` on each of your pages. Let me know if that doesn't work for you.

**Comment by ABooth01** [comment]
Thank you Blackary! I missed this and was an easy fix.
