### ISSUE TITLE
hide_pages is buggy: starts hidden, but reappears as soon as any page is accessed.

### ISSUE THREAD

**Issue by victorccaldas** [blackary/st_pages#34]
Code:

```

show_pages(
        [
            Page("paginas/dashboard.py", "Dashboard", "📊"),

            Page("paginas/ferramentas.py", "Tools", "⚙️"),
            
            Page("paginas/docs.py", "Docs", "🧾"),
            
            Page("paginas/finance.py", "Finance", "💲")
        ]
    )

hide_pages(["Tools"])

```

**Comment by blackary** [comment]
You have to use hide_pages on every page that you want pages hidden from. It would be possible to make it permanent, but right now this is the behavior by design. I added an issue for the future if someone wants to add that new functionality https://github.com/blackary/st_pages/issues/35
