### ISSUE TITLE
Conflict with set_page_config method

### ISSUE THREAD

**Issue by victorccaldas** [blackary/st_pages#36]
While trying to set my layout as wide with `set_page_config(layout='wide')`, I get the error `StreamlitAPIException: 'set_page_config()' can only be called once per app, and must be called as the first Streamlit command in your script.` because it seems like `set_page_config()` is probably called on any of the imports `from st_pages import Page, Section, show_pages, hide_pages`

**Comment by blackary** [comment]
`set_page_config` is only called in `add_page_title()`. You can pass `layout="wide"` to `add_page_title`. See https://github.com/blackary/st_pages/blob/main/example_app/example_one.py for an example

**Comment by victorccaldas** [comment]
I have not called add_page_title() in any part of my code, so based on your explanation it shouldn't return the StreamlitAPIException but it does. Gotta investigate why might that be

**Comment by blackary** [comment]
Oh, that's not great -- let me know if you track down where it's being called

**Comment by victorccaldas** [comment]
probably in line 102 of your init file: `add_page_title = _gather_metrics("st_pages.add_page_title", _add_page_title)`

**Comment by victorccaldas** [comment]
> Oh, that's not great -- let me know if you track down where it's being called

seems to be in line 102 of your init file: `add_page_title = _gather_metrics("st_pages.add_page_title", _add_page_title)`

**Comment by blackary** [comment]
No, that doesn't actually call the `_add_page_title` method, it just wraps it in a metrics method.

**Comment by Ubinazhip** [comment]
Yes, I have same problem. I don't call add_page_title() function, but somewhere in your code it calls set_page_config, which conflicts with my set_page_config

**Comment by victorccaldas** [comment]
Actually the error `StreamlitAPIException: 'set_page_config()' can only be called once per app, and must be called as the first Streamlit command in your script.` catches not one, but two possible errors.
The first possible error is trying to call set_page_config() twice, which we think is not the case here.
The second possible error is calling a Streamlit command before set_page_config(), which might be the case here.

The problem probably is that the imports of st_pages call some Streamlit commands, which causes the conflict when we try to call set_page_config() for the first time, triggering the error since Streamlit commands have already being called somewhere.

**Comment by blackary** [comment]
Can you @victorccaldas or @Ubinazhip share a minimal app which reproduces this error?
