### ISSUE TITLE
hide_pages interferes with st.selectbox

### ISSUE THREAD

**Issue by blenzi** [blackary/st_pages#38]
Hi,

When using `hide_pages`, it hides not only the pages but also some options of a selectbox. To reproduce it, add to https://github.com/blackary/st_pages/blob/main/example_app/example_four.py:

```
st.selectbox("test_select", options=["1", "2", "3"])
```

Output:

![Screenshot 2023-04-14 at 13 18 41](https://user-images.githubusercontent.com/14099304/232030463-efe44dea-befd-49db-af39-5c1f86c95021.png)
![Screenshot 2023-04-14 at 13 18 48](https://user-images.githubusercontent.com/14099304/232030477-ec193a72-a337-4481-ba2b-1acc3301e4d5.png)

**Comment by mfriedy** [comment]
@blackary  - are you able to check out the PR to see if you think it is a robust-enough fix for this issue? Thanks!

**Comment by blackary** [comment]
Hi @mfriedy, thanks for the ping. I haven't been able to test out the PR yet, but will try to do so today.

**Comment by blackary** [comment]
Fixed via #39
