### ISSUE TITLE
Sections Not working as expected

### ISSUE THREAD

**Issue by benseddikmo** [blackary/st_pages#41]
Hello,

I am trying to instantiate sections in my streamlit app, but It behaves as a Page.
I can click on the Section without any link or app behind, and I do not have the hierarchy of Sections - Pages I expected.

**Comment by WudiJoey** [comment]
hi， i think maybe you not set the first page as your main.py

**Comment by blackary** [comment]
@benseddikmo You must call add_page_title() or add_indentation() on each page if you want sections to work properly.
