### ISSUE TITLE
st.header() anchor links do not work

### ISSUE THREAD

**Issue by justkrys** [blackary/st_pages#43]
Hi.  I just noticed that the #anchor links included with, say, st.header() do not work on st-pages pages.  Instead one just gets redirected to the root/main page.

I double checked and anchor links in regular Streamlit pages/foo do work.  So, I believe the issue is specific to st-pages.

**Comment by blackary** [comment]
Yup, that's definitely a bug -- no idea why that's happening, but I can confirm it from the example app 😬

**Comment by bastgau** [comment]
Seems to work when the pages don't contain a space character in their name.

When a page contains a space character, the anchors don't work anymore.
