### ISSUE TITLE
drawing canvas does not work in combination with st_pages

### ISSUE THREAD

**Issue by janezlapajne** [blackary/st_pages#44]
Hello,

I am posting the [issue](https://github.com/andfanilo/streamlit-drawable-canvas/issues/119) here as well as on canvas repo, since I am unsure on which side the problem lies.  I hope the issue can be resolved easily :)

**Comment by blackary** [comment]
I would guess this will now be resolved if you switch to the st.navigation-based 1.0.0 release of this package
