### ISSUE TITLE
Streamlit 1.23.1 breaking rerun on changes for pages

### ISSUE THREAD

**Issue by mfriedy** [blackary/st_pages#46]
After upgrading to 1.23.1 of Streamlit, all of a sudden any pages do not capture changes when rerunning after saving.

In some cases it notifies that the file has changed, but rerunning the page does not reflect the updated report.

Simple replication:

- install st_pages 0.4.1 and streamlit 1.22.0 for an app with 1 subpage
- confirm that changing subpage (e.g. st.write) updates when changed
- update to streamlit 1.23.1
- the subpage now no longer will update

Not sure where this bug actually lies. But given a "normal" streamlit multipage app seems OK, is it something how st_pages registers the pages?

**Comment by mfriedy** [comment]
Could it have something to do with: https://github.com/streamlit/streamlit/commit/26f97dfb26e6eea557bb953d4fcf5e298e1a20d7

**Comment by mfriedy** [comment]
I've been digging around in some spare time and think it is because the Script cache has its own "local file watcher" which only registers the entry file, and then things in the pages directory.

When st_pages then adjusts the list of pages, this doesnt then update the script cache? 

(not 100% sure this is it, but its my current hunch)

i.e. in runtime.py
```python
       self._sources_watcher = LocalSourcesWatcher(self._main_script_path)
        self._sources_watcher.register_file_change_callback(
            lambda _: self._script_cache.clear()
        )
```

I'm trying to understand it all, but not sure if this needs to be a fix to streamlit to update the script cache when something changes, or if st_pages needs to fire some other event to get the update

**Comment by dzmitry-kankalovich** [comment]
I'm not sure it is the same root cause, but just in case: https://github.com/blackary/st_pages/issues/52
