### ISSUE TITLE
Support top tab menu

### ISSUE THREAD

**Issue by ulhaqi12** [blackary/st_pages#50]
Hi,

I am developing an application using streamlit and after using this package my code is a lot cleaner. Thank you for that. I have a suggestion, with a side menu, can we also provide an option for the top menu? Like names of the pages appearing on the top with icons.
Thank you

BR,
Ikram

**Comment by blackary** [comment]
That's an interesting idea, but since the current package is built on top of the existing streamlit multipage functionality, I don't think I will add a top navbar anytime soon.
