### ISSUE TITLE
Sections not working correctly

### ISSUE THREAD

**Issue by Thunder7754** [blackary/st_pages#54]
Hey Guys, 
I experienced a problem with the sections, with my personal project as well as with your examples. They get displayed as normal pages and when i click on them, i get redirected to the page above. I used both methods to create sections and the results were the same. 

I am using streamlit 1.25.0 and st-pages 0.4.3

Thanks in advance!

**Comment by blackary** [comment]
Could you share an example repo which shows this issue?

**Comment by Thunder7754** [comment]
This occured in the example projects in this repo for me as well.

**Comment by 0ptimista** [comment]
Same promblem, I am using a config file.

**Comment by blackary** [comment]
I'm so sorry, I'm trying to reproduce this but struggling. Do you have an example repo where you are seeing this issue?

You can see in the example app https://st-pages-sections.streamlit.app/ that it's working well, even after I explicitly updated the version numbers in requirements.txt

**Comment by 0ptimista** [comment]
I created a demo repo here https://github.com/0ptimista/stpage-test
Inside `src` folder when I run `streamlit run stpage-test/home.py` the `Section` part is clickable which shoud not.

**Comment by blackary** [comment]
Thanks for the example! That's very helpful. The main issue is that you have to call `add_page_title()` or `add_indentation()` on *every* page in order to add the indentation and make the Section not clickable, since that is done via CSS.

If you add those to every page, you should be good to go.

**Comment by 0ptimista** [comment]
Oh! Thanks for replying! How can I miss the bottom of README! 

It now act as it should be after add `add_indentation()` at every page!

Really helped me out!
