### ISSUE TITLE
Remove numpy dependency specification

### ISSUE THREAD

**Issue by Wazarr94** [blackary/st_pages#56]
Would it be possible to remove numpy from pyproject.toml?
I'm trying to use this library but I cannot install this library with poetry because I have numba v0.55.2, and numba requires numpy<1.23 while st_pages requires numpy>=1.23.4.

And from the src folder, it doesn't look like numpy is needed as an upfront dependency.
Thanks

**Comment by blackary** [comment]
To be honest, I'm not sure why I put that in. I think it should be fine to drop it, but would need to run the test suite to make sure.

**Comment by CHerSun** [comment]
> To be honest, I'm not sure why I put that in. I think it should be fine to drop it, but would need to run the test suite to make sure.

most likely you just locked every package that was installed, not what you actually use
