### ISSUE TITLE
Bad message format Cannot read properties of undefined (reading 'pageScriptHash')

### ISSUE THREAD

**Issue by bonfire27** [blackary/st_pages#69]
When I am interacting with a page (therefore causing reruns) and the icons for the pages are appearing normally (there's times that they don't appear) I sometimes get the message on streamlit:

> **Bad message format**
> Cannot read properties of undefined (reading 'pageScriptHash')

It will also sometimes if I am not in the main page redirect you to a page _http://localhost:8501/undefined_ that doesn't exist. If i enter that url in the browser it gives "page not found". 
if you keep interacting with this ghost page it will go back to the real one eventually. But in these changes back and forth from the ghost page all the session_state is lost  which is pretty annoying and makes the app unusable.

The bug though disappears if I use version` st-pages==0.4.1` and I think it's related to the component `st_aggrid` because only when I have an AgGrid that the ghost page and session state delete occurs. For the other pages it's only the message `Bad message format Cannot read properties of undefined (reading 'pageScriptHash')`

This is related to this post I made in the streamlit forums:
https://discuss.streamlit.io/t/using-aggrid-sometimes-changes-the-page-to-undefined-reseting-the-session-state/50090

**Comment by tidalmelon** [comment]
I return `st-pages` vision to 0.4.1, when I refresh the main page: `http://*.*.*.*:8501` frequently.  the `pageScriptHash` will be shown a low probability.  my streamlit version is `1.30.0`

**Comment by unfailingsalvage1448** [comment]
did either of you find a solution to this problem?
