### ISSUE TITLE
Do not work for Streamlit 1.2.7 version

### ISSUE THREAD

**Issue by ZefengQiu196** [blackary/st_pages#74]
I tried the code in Streamlit 1.2.7, but the section function does not work: The section becomes clickable, the content is the same as the home page, and the location of pages under the section at the sidebar is the same as pages out of the section

**Comment by rajesh-ahana** [comment]
Having the same issue

**Comment by yash2mehta** [comment]
Same issue as well, pls fix

**Comment by aaronpliu** [comment]
same issue in v1.28

**Comment by Karlosll91** [comment]
V1. 28, same problem today

**Comment by blackary** [comment]
Thanks for the feedback -- could someone please share a simple example repo and app that shows this problem?

**Comment by Karlosll91** [comment]
Thank you blackary, please check https://github.com/Karlosll91/streamlit_test

I have Python==3.11.5, Streamlit==1.28.0 and st-pages==0.4.5

When I load the app, it looks like is working only in the main page but when I change pages it loses indentation, and sections become clickable. I tried adding show_pages code to all other pages but same thing happens

**Comment by blackary** [comment]
@Karlosll91 Note that `add_page_title()` or `add_indentation()` *must* be called on every page in the app to add the indentation and to make the section unclickable.

**Comment by Karlosll91** [comment]
You are totally right, that solves the problem! thank you. This was my first time using the module and totally missed the comment in the code in the last example of the README. I think I missed because just wanted to use the show_pages function so I just quickly looked over the rest of examples, might I suggest adding the note to the first example too? thanks @blackary

**Comment by blackary** [comment]
@Karlosll91 Good point. I added it to the first section about using sections.
<img width="1050" alt="image" src="https://github.com/blackary/st_pages/assets/4040678/dd0ef30c-7cef-4dd4-bf60-9cf02ca16638">
