### ISSUE TITLE
Codec error on Windows

### ISSUE THREAD

**Issue by cbpeters** [blackary/st_pages#78]
Users running streamlit and st_pages on windows receive a Codec error due to missing an encoding specification.
 
The get_icons() function should specify encoding="utf-8" parameter when reading in the emoji file.

**Comment by blackary** [comment]
It does, as of version 0.4.5 https://github.com/blackary/st_pages/commit/1c41d5b1cd76201f0d7e5ed0e4a4fcf2720d7760
