### ISSUE TITLE
sections should not be clickable + section content

### ISSUE THREAD

**Issue by tombeteende** [blackary/st_pages#88]
I init the pages via a config file (see example below) where I have a home page and two sections. The home page has some content in it.

The sections are clickable and the content it displays is the content of the homepage.
I would expect it to be unclickable or controllable and not display the content of the home page. What can I do about it?

Additionally, is there away I can control the size of the indentation?

```
[[pages]]
path = "home_page.py"
name = "Home"
icon = ":sunflower:"

[[pages]]
name = "Section 1"
icon = ":phone:"
is_section = true

[[pages]]
path = "pages/01_example.py"
name = "01 example"
icon = ":fortune_cookie:"
in_section = true


[[pages]]
name = "Section 2"
icon = ":phone:"
is_section = true

[[pages]]
path = "pages/02_example.py"
name = "02 example"
icon = ":fortune_cookie:"
in_section = true
```

**Comment by jamesxu0220** [comment]
Are you calling add_indentation() on every page? Once i did that it removed this behavior.

**Comment by Sairam90** [comment]
still show home page on sections

**Comment by blackary** [comment]
Should be resolved by this method https://github.com/blackary/st_pages/issues/88#issuecomment-1939185685
