### ISSUE TITLE
Can I not indenet? (For not causing flicker)

### ISSUE THREAD

**Issue by tmactodarack** [blackary/st_pages#93]
Thanks for this great library

Im wondering if it is possible to not indent child page after section for it causes flicker
I know there I can make "is_section" = false to restrain the indent
However, that seems not working pretty well (cannot achieve what I expect that all the child pages not indent)

I think even not indenting, still can make a good tree like menu so I would recommend to add a function not indenting 

Thanks!

**Comment by blackary** [comment]
You can use `add_page_title(also_indent=False)`
